steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-binskim.BinSkim@3
  displayName: 'Run BinSkim'
  inputs:
    InputType: Basic
    AnalyzeTarget: '$(DropPath)\*.dll;$(DropPath)\*.exe'
  continueOnError: true
  condition: eq(variables['ENABLE_COMPLIANCE'], 'true')

- task: securedevelopmentteam.vss-secure-development-tools.build-task-roslynanalyzers.RoslynAnalyzers@2
  displayName: 'Run Roslyn Analyzers'
  continueOnError: true
  condition: eq(variables['ENABLE_COMPLIANCE'], 'true')

- task: ms-vseng.MicroBuildShipTasks.7c429315-71ba-4cb3-94bb-f829c95f7915.MicroBuildCodesignVerify@2
  displayName: 'Verify Signed Files'
  inputs:
    TargetFolders: '$(DropPath)'

- task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
  displayName: 'Publish Security Analysis Logs'
  condition: eq(variables['ENABLE_COMPLIANCE'], 'true')

- task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
  displayName: 'Post Analysis'
  inputs:
    AllTools: true
  condition: eq(variables['ENABLE_COMPLIANCE'], 'true')
